### ISSUE TITLE
InstagramAPI

### ISSUE THREAD

**Issue by mio256** [jphacks/E_2205#8]

**Comment by koyo343** [comment]
Instagram Graph APIからデータ取得　トークン延長

**Comment by mio256** [comment]
Instagrapi
https://adw0rd.github.io/instagrapi/
を使ってみる

**Comment by koyo343** [comment]
Graph APIのリファレンス https://developers.facebook.com/docs/instagram-api/reference
Basic Display APIのリファレンス https://developers.facebook.com/docs/instagram-basic-display-api/reference
Meta https://developers.facebook.com/apps/1236684910520924/settings/basic/
